### ISSUE TITLE
[FEATURE]: Run Id should be available in a process

### ISSUE THREAD

**Issue by themasterlink** [evhub/bbopt#16]
While using bbopt each run process has its own run id, which is not available during each run. 

It would be awesome if the run id can either be accessed via the `BlackBoxOptimizer` object or via an environment variable, which has to be then set for each process.

**Comment by evhub** [comment]
@themasterlink Thanks for the issue! This should now be available as `bbopt.run_id` on `bbopt>=1.3.7`.
